export const CAR_LIST_REQUEST='CAR_LIST_REQUEST'
export const CAR_LIST_SUCCESS='CAR_LIST_SUCCESS'
export const CAR_LIST_FAIL='CAR_LIST_FAIL' 

export const ADD_CAR_REQEUST='ADD_CAR_REQUEST'
export const ADD_CAR_SUCCESS='ADD_CAR_SUCCESS'
export const ADD_CAR_FAIL='ADD_CAR_FAIL'

export const MODIFY_CAR_REQEUST='MODIFY_CAR_REQUEST'
export const MODIFY_CAR_SUCCESS='MODIFY_CAR_SUCCESS'
export const MODIFY_CAR_FAIL='MODIFY_CAR_FAIL'

export const DELETE_CAR_REQEUST='DELETE_CAR_REQUEST'
export const DELETE_CAR_SUCCESS='DELETE_CAR_SUCCESS'
export const DELETE_CAR_FAIL='DELETE_CAR_FAIL'

