# Generated by Django 4.2.7 on 2024-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icone',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
