# Generated by Django 4.2.7 on 2024-05-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_service_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
