# Generated by Django 4.2.7 on 2024-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_service_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='chassis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
