# Generated by Django 4.2.7 on 2024-04-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_is_active_alter_newuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
